- composer.json
- init.sh
- scaffold_tests/init.bats
- template-command-script
> Moved PHP command bin into root and fixed init.

- init.sh
- scaffold_tests/init.bats
> Added selection for Renovate.

- .github/workflows/test.yml
- .gitignore
- phpunit.xml
> Fixed coverage file name.

- .gitattributes
- .gitignore
- init.sh
- tests/scaffold/_assert.bash
- tests/scaffold/init.bats
> Fixed replacements not working in dotfiles.

- .github/workflows/scaffold-test.yml
- .github/workflows/test.yml
Swapped `php-actions/composer@v6` with `shivammathur/setup-php@v2`.
> Replaced PHP GitHub action to install PHP into the runner container.

- .gitattributes
- init.sh
- tests/scaffold/_assert_init.bash
> Fixed processing of .gitattributes based on selected features.

- .github/workflows/test.yml
- composer.json
- package.json
> Added support for PHP and NodeJS version matrices.

- .github/release-drafter.yml
> [#53] Updated release drafter config to use resolved version.

- .github/workflows/test.yml
closes https://github.com/AlexSkrypnyk/scaffold/issues/40
> Added build-php job to CI.

- .github/workflows/test-scaffold.yml
- .github/workflows/test-shell.yml
- .gitignore
- README.md
- docs/Gemfile.lock
- docs/_config.yml
- docs/ci/test.md
- docs/php/php-command.md
- docs/php/php-script.md
- docs/shell/index.md
- docs/shell/linting.md
- docs/shell/shell-command.md
- docs/shell/testing.md
- init.sh
- shell-command.sh
- tests/bats/.gitignore
- tests/bats/_helper.bash
- tests/bats/package-lock.json
- tests/bats/package.json
- tests/bats/shell-command.bats
- tests/scaffold/_assert_init.bash
- tests/scaffold/functional.init.bats
> [#15] Added support for Shell command.

- .github/workflows/test-nodejs.yml
- .github/workflows/test-php.yml
- .github/workflows/test-shell.yml
- docs/ci/test.md
> [#116] Added flags to ignore lint and test failures in CI.

- README.dist.md
> [#117] Added CLI commands table to readme.

- .github/PULL_REQUEST_TEMPLATE.md
> [#107] Simplified PR template.

- .github/FUNDING.yml
> [#108] Added GitHub sponsorship.

- .github/.yamllint-for-gha.yml
- .github/workflows/release-php.yml
- .github/workflows/test-actions.yml
- .github/workflows/test-php.yml
- .github/workflows/test-scaffold.yml
- docs/content/ci/test.mdx
> [#143] Added linting of the GitHub actions.

- php-script
- phpcs.xml
- rector.php
- src/Command/JokeCommand.php
- src/Command/SayHelloCommand.php
- src/app.php
- tests/phpunit/Functional/ExampleScriptFunctionalTest.php
- tests/phpunit/Functional/ScriptFunctionalTestCase.php
- tests/phpunit/Traits/ArrayTrait.php
- tests/phpunit/Traits/AssertTrait.php
- tests/phpunit/Traits/ClosureWrapperTrait.php
- tests/phpunit/Traits/EnvTrait.php
- tests/phpunit/Traits/MockTrait.php
- tests/phpunit/Traits/ReflectionTrait.php
- tests/phpunit/Traits/VfsTrait.php
- tests/phpunit/Unit/Command/CommandTestCase.php
- tests/phpunit/Unit/Command/JokeCommandTest.php
- tests/phpunit/Unit/Command/SayHelloCommandTest.php
- tests/phpunit/Unit/ExampleScriptUnitTest.php
- tests/phpunit/Unit/ScriptUnitTestCase.php
> [#158] Updated Rector rules to force declare strict type

- .github/workflows/release-php.yml
- .github/workflows/test-php.yml
- composer.json
- docs/content/php/composer.mdx
- rector.php
> [#127] Removed support  for PHP 8.1.

- tests/scaffold/functional.init.bats
- tests/scaffold/unit.init.bats
Closes #169 
1. Increased coverage for init.sh 
https://app.codecov.io/gh/AlexSkrypnyk/scaffold/pull/170/indirect-changes
> [#169] Increased coverage for `init.sh` script

- init.sh
- tests/scaffold/functional.init.bats
> [#171] Handle invalid project name in init.sh

- init.sh
- tests/scaffold/functional.init.bats
- tests/scaffold/unit.init.bats
> [#172] Handle invalid namespace in init.sh

- .github/workflows/test-scaffold.yml
- .github/workflows/test-shell.yml
- phpunit.xml
> [#165] Excluded tests' code from coverage.

- .github/workflows/test-php.yml
> [#166] Replaced PHP coverage driver to use `pcov`.

- .github/workflows/test-php.yml
- composer.json
> [#186] Added normalizer for `composer.json`.

- .github/workflows/test-nodejs.yml
- docs/content/nodejs/README.mdx
- package.json
> Updated CI to use NodeJS 22.

- composer.json
- init.sh
- phpunit.xml.bak
- tests/phpunit/Functional/ExampleScriptFunctionalTest.php
- tests/phpunit/Unit/Command/JokeCommandTest.php
- tests/phpunit/Unit/Command/SayHelloCommandTest.php
- tests/phpunit/Unit/ExampleScriptUnitTest.php
- tests/scaffold/_assert_init.bash
> [#187] Updated to PHPUnit 11 and moved to attributes in tests.

- .github/workflows/test-nodejs.yml
- .github/workflows/test-php.yml
- .github/workflows/test-scaffold.yml
- .github/workflows/test-shell.yml
- docs/content/ci/README.mdx
- docs/cspell.json
`lhotari/action-upterm` is not maintained since 2021 and has issues with running inside of the containerised environments.
> Replaced `upterm` with `tmate`.

- .github/workflows/test-php.yml
> Added PHP 8.4 support.
